name: Test on Linux runner
on:
  push:

jobs:
  protocol:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup Grafana k6
      uses: ./
      with:
        k6-version: '0.57.0'
    - run: k6 run ./dev/protocol.js --quiet

  browser:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup Grafana k6
      uses: ./
      with:
        k6-version: '0.57.0'
        browser: true
    - run: k6 run ./dev/browser_linux.js --quiet

  use-latest-release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup Grafana k6
      uses: ./
    - run: k6 run ./dev/protocol.js --quiet